# Generated by Django 3.2.9 on 2021-11-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persistent_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('file_name', models.TextField()),
                ('model_type', models.TextField()),
                ('num_topics', models.IntegerField()),
                ('normalisation', models.TextField()),
            ],
        ),
    ]
