# Generated by Django 3.2.9 on 2021-11-03 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage_services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persistent_storage',
            name='id',
        ),
        migrations.AddField(
            model_name='persistent_storage',
            name='save_model',
            field=models.FileField(default='', upload_to='models'),
        ),
        migrations.AlterField(
            model_name='persistent_storage',
            name='name',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
