# Generated by Django 3.2.9 on 2021-11-03 20:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage_services', '0002_auto_20211103_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistent_storage',
            name='name',
            field=models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
