# Generated by Django 3.2.9 on 2021-11-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_services', '0004_persistent_storage_topic_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistent_storage',
            name='topic_labels',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
